#pragma config(Motor,  port1,           flywheelLeft,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           shooterConvayerLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           intakeConvayer, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rampLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rampRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           shooterConvayerRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           driveRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          flywheelRight, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................
	  // Insert user code here. This is where you use the joystick values to update your motors, etc.
	  // .....................................................................................
  	//motors direct mapping from up/down joysticks
  	motor[driveRight] = vexRT[Ch2];
  	motor[driveLeft] = vexRT[Ch3];

  	//flywheel control code
  	if(vexRT[Btn8D]){
  		motor[flywheelLeft] = 110;
  		motor[flywheelRight] = 110;
  	}
  	if(vexRT[Btn8R]){
  		motor[flywheelLeft] = 90;
  		motor[flywheelRight] = 90;
  	}
  	if(vexRT[Btn8U]){
  		motor[flywheelLeft] = 0;
  		motor[flywheelRight] = 0;
  	}

  	//ramp control code

  	//right
  	if(vexRT[Btn6U]){
  		motor[rampRight] = 127;
  	}
  	else if(vexRT[Btn6D]){
  		motor[rampRight] = -127;
  	}
  	else{
  		motor[rampRight] = 0;
  	}
  	//left
  	if(vexRT[Btn5U]){
  		motor[rampLeft] = 127;
  	}
  	else if(vexRT[Btn5D]){
  		motor[rampLeft] = -127;
  	}
  	else{
  		motor[rampLeft] = 0;
  	}

  	//shooter convayer control code
  	if(vexRT[Btn7D]){
  		motor[shooterConvayerLeft] = 127;
  		motor[shooterConvayerRight] = 127;
  	}
  	if(vexRT[Btn7U]){
  		motor[shooterConvayerLeft] = 0;
  		motor[shooterConvayerRight] = 0;
  	}

  	//intake control code
  	if(vexRT[Btn7L]){
  		motor[intakeConvayer] = 127;
  	}
  	if(vexRT[Btn7R]){
  		motor[intakeConvayer] = 0;
  	}




	  UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
	}
}
